<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>piekarski_gov51_final_paper</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="piekarski_gov51_finalpaper_files/libs/clipboard/clipboard.min.js"></script>
<script src="piekarski_gov51_finalpaper_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="piekarski_gov51_finalpaper_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="piekarski_gov51_finalpaper_files/libs/quarto-html/popper.min.js"></script>
<script src="piekarski_gov51_finalpaper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="piekarski_gov51_finalpaper_files/libs/quarto-html/anchor.min.js"></script>
<link href="piekarski_gov51_finalpaper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="piekarski_gov51_finalpaper_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="piekarski_gov51_finalpaper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="piekarski_gov51_finalpaper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="piekarski_gov51_finalpaper_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">piekarski_gov51_final_paper</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="can-we-predict-what-nhl-players-are-likely-to-have-a-breakout-season-evaluating-moneypuck" class="level1">
<h1>Can We Predict What NHL Players Are Likely To Have A Breakout Season? Evaluating MONEYPUCK</h1>
<section id="by-sage-piekarski" class="level4">
<h4 class="anchored" data-anchor-id="by-sage-piekarski">By: Sage Piekarski</h4>
<p>Predictive Report</p>
<p>Gov 51: Data Analysis and Politics</p>
<p>Professor Cunningham</p>
<p>2026 - 05 - 11</p>
<p><a href="https://github.com/sagepiekarski-ai/Gov51---Final-Paper.git" class="uri">https://github.com/sagepiekarski-ai/Gov51---Final-Paper.git</a></p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1 Introduction</h2>
<p>The National Hockey League is growing faster than ever before. With an average 15% year over year growth in each individual teams’ valuation, the average of team valuations has more than doubled from $1billion in 2022 to $2.2 billion in 2024. Certainly there is a spectrum of team valuations within these means, but both ends are experiencing large increases in their valuations. For instance, the Columbus Blue Jackets is the lowest valuated team in all of the NHL, yet there valuation has jumped 30% since 2024, reaching $1.3 billion. On the flip side, the Toronto Maple Leafs continue to be the highest valuated team in the league, growing 16% since 2024, to a value of $4.4 billion.</p>
<p>All things considered, as the NHL continues to skyrocket into unchartered territory, the stakes and performances of each one of the 32 franchises becomes increasingly important. While there is a bounty of data detailling NHL performance statistics, like MoneyPuck, modern day ice hockey statistics fail to provide complete predictive models of what players are most likely to have a standout season in the future.</p>
<p>To that end, this paper seeks to use past player performance statistics collected in MoneyPuck, to predict which NHL players have the highest probability of having a breakout season. Four questions guide the paper’s progression: how well do observable performance statistics predict breakout rate, does shrinkage using LASSO improve prediction compared to a traditional LPM or Logit model, does the model predict fairly across positions, and what players have had the largest predicted probability of having a breakout season in their next year of play.</p>
<p>We find that across three tested models an OLS Baseline, Logit, and LASSO, the Logit has the highest performance with a test RMSE of 0.3091 and a test accuracy of 54.8%. Using cross-validation to select a lambda for LASSO over Logit, did not prove to yield substantially different results. Within these models, we determine that shots per game is the strongest predictor of a breakout season next season, while games played, expected goals, and being a defender are negatively associated with future breakout. The Logit model does predict fairly evenly across positions with slight overprediction for centers and defenders and slight underprediction for right wings and left wings. Ultimately, our results reveal that while predicting breakout players is possible it is a very challenging feat to do accurately with our best model holding a 54.8% test accuracy.</p>
<p><a href="https://www.forbes.com/sites/justinteitelbaum/2025/12/11/the-nhls-most-valuable-teams-2025/" class="uri">https://www.forbes.com/sites/justinteitelbaum/2025/12/11/the-nhls-most-valuable-teams-2025/</a></p>
</section>
<section id="data-and-measurement" class="level2">
<h2 class="anchored" data-anchor-id="data-and-measurement">2 Data and Measurement</h2>
<section id="the-moneypuck-dataset" class="level3">
<h3 class="anchored" data-anchor-id="the-moneypuck-dataset">2.1 The MONEYPUCK Dataset</h3>
<p>The data used in this project comes from the MoneyPuck dataset. MoneyPuck data and its models were compiled and put together by Peter Tanner. The data used in this project consists of season-level data from the 2008/2009 season to the 2024/2025 season. We evaluate all players who played greater than zero games, and who were identified as skaters.</p>
<p>The dataset contains 76,655 observations across 154 variables and each unit of observation is a player-season.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#clear the workspace and clear console</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">'</span><span class="sc">\014</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div style="page-break-after: always;"></div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Install and load packages</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(tidyverse)) <span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>); <span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(dplyr)) <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>); <span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(glmnet)) <span class="fu">install.packages</span>(<span class="st">"glmnet"</span>);<span class="fu">library</span>(glmnet)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: glmnet
Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack

Loaded glmnet 4.1-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(knitr)) <span class="fu">install.packages</span>(<span class="st">"knitr"</span>);<span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: knitr</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(scales)) <span class="fu">install.packages</span>(<span class="st">"scales"</span>);<span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: scales

Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#read csv</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>skaters_2008_to_2024 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Data/Raw/skaters_2008_to_2024.csv"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co">#glimpse &amp; understand data</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(skaters_2008_to_2024)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 76,655
Columns: 154
$ playerId                                                &lt;int&gt; 8462196, 84621…
$ season                                                  &lt;int&gt; 2008, 2008, 20…
$ name                                                    &lt;chr&gt; "Stephane Robi…
$ team                                                    &lt;chr&gt; "DAL", "DAL", …
$ position                                                &lt;chr&gt; "D", "D", "D",…
$ situation                                               &lt;chr&gt; "other", "all"…
$ games_played                                            &lt;int&gt; 72, 72, 72, 72…
$ icetime                                                 &lt;dbl&gt; 6729, 105958, …
$ shifts                                                  &lt;dbl&gt; 105, 2026, 148…
$ gameScore                                               &lt;dbl&gt; 31.93, 31.71, …
$ onIce_xGoalsPercentage                                  &lt;dbl&gt; 0.51, 0.53, 0.…
$ offIce_xGoalsPercentage                                 &lt;dbl&gt; 0.36, 0.45, 0.…
$ onIce_corsiPercentage                                   &lt;dbl&gt; 0.59, 0.53, 0.…
$ offIce_corsiPercentage                                  &lt;dbl&gt; 0.46, 0.49, 0.…
$ onIce_fenwickPercentage                                 &lt;dbl&gt; 0.58, 0.53, 0.…
$ offIce_fenwickPercentage                                &lt;dbl&gt; 0.46, 0.50, 0.…
$ iceTimeRank                                             &lt;dbl&gt; 134, 114, 160,…
$ I_F_xOnGoal                                             &lt;dbl&gt; 22.30, 163.56,…
$ I_F_xGoals                                              &lt;dbl&gt; 1.91, 9.17, 2.…
$ I_F_xRebounds                                           &lt;dbl&gt; 1.59, 11.35, 3…
$ I_F_xFreeze                                             &lt;dbl&gt; 4.82, 38.96, 1…
$ I_F_xPlayStopped                                        &lt;dbl&gt; 0.81, 5.25, 2.…
$ I_F_xPlayContinuedInZone                                &lt;dbl&gt; 14.80, 104.62,…
$ I_F_xPlayContinuedOutsideZone                           &lt;dbl&gt; 8.20, 69.79, 3…
$ I_F_flurryAdjustedxGoals                                &lt;dbl&gt; 1.80, 8.65, 2.…
$ I_F_scoreVenueAdjustedxGoals                            &lt;dbl&gt; 1.91, 9.14, 2.…
$ I_F_flurryScoreVenueAdjustedxGoals                      &lt;dbl&gt; 1.80, 8.62, 2.…
$ I_F_primaryAssists                                      &lt;dbl&gt; 3, 12, 6, 0, 3…
$ I_F_secondaryAssists                                    &lt;dbl&gt; 1, 11, 6, 1, 3…
$ I_F_shotsOnGoal                                         &lt;dbl&gt; 24, 158, 65, 5…
$ I_F_missedShots                                         &lt;dbl&gt; 10, 83, 34, 1,…
$ I_F_blockedShotAttempts                                 &lt;dbl&gt; 16, 101, 47, 1…
$ I_F_shotAttempts                                        &lt;dbl&gt; 50, 342, 146, …
$ I_F_points                                              &lt;dbl&gt; 4, 26, 14, 1, …
$ I_F_goals                                               &lt;dbl&gt; 0, 3, 2, 0, 1,…
$ I_F_rebounds                                            &lt;dbl&gt; 1, 13, 6, 0, 6…
$ I_F_reboundGoals                                        &lt;dbl&gt; 0, 0, 0, 0, 0,…
$ I_F_freeze                                              &lt;dbl&gt; 3, 32, 17, 1, …
$ I_F_playStopped                                         &lt;dbl&gt; 2, 8, 3, 0, 2,…
$ I_F_playContinuedInZone                                 &lt;dbl&gt; 18, 112, 38, 1…
$ I_F_playContinuedOutsideZone                            &lt;dbl&gt; 10, 73, 33, 4,…
$ I_F_savedShotsOnGoal                                    &lt;dbl&gt; 24, 155, 63, 5…
$ I_F_savedUnblockedShotAttempts                          &lt;dbl&gt; 34, 238, 97, 6…
$ penalties                                               &lt;dbl&gt; 3, 39, 30, 2, …
$ I_F_penalityMinutes                                     &lt;dbl&gt; 6, 76, 60, 4, …
$ I_F_faceOffsWon                                         &lt;dbl&gt; 0, 1, 1, 0, 0,…
$ I_F_hits                                                &lt;dbl&gt; 9, 221, 162, 3…
$ I_F_takeaways                                           &lt;dbl&gt; 2, 28, 17, 5, …
$ I_F_giveaways                                           &lt;dbl&gt; 3, 44, 33, 4, …
$ I_F_lowDangerShots                                      &lt;dbl&gt; 28, 221, 97, 5…
$ I_F_mediumDangerShots                                   &lt;dbl&gt; 4, 14, 2, 1, 7…
$ I_F_highDangerShots                                     &lt;dbl&gt; 2, 6, 0, 0, 4,…
$ I_F_lowDangerxGoals                                     &lt;dbl&gt; 0.92, 5.32, 1.…
$ I_F_mediumDangerxGoals                                  &lt;dbl&gt; 0.46, 1.71, 0.…
$ I_F_highDangerxGoals                                    &lt;dbl&gt; 0.53, 2.14, 0.…
$ I_F_lowDangerGoals                                      &lt;dbl&gt; 0, 2, 2, 0, 0,…
$ I_F_mediumDangerGoals                                   &lt;dbl&gt; 0, 1, 0, 0, 1,…
$ I_F_highDangerGoals                                     &lt;dbl&gt; 0, 0, 0, 0, 0,…
$ I_F_scoreAdjustedShotsAttempts                          &lt;dbl&gt; 50.00, 340.26,…
$ I_F_unblockedShotAttempts                               &lt;dbl&gt; 34, 241, 99, 6…
$ I_F_scoreAdjustedUnblockedShotAttempts                  &lt;dbl&gt; 34.00, 240.05,…
$ I_F_dZoneGiveaways                                      &lt;dbl&gt; 0, 31, 27, 4, …
$ I_F_xGoalsFromxReboundsOfShots                          &lt;dbl&gt; 0.49, 2.71, 0.…
$ I_F_xGoalsFromActualReboundsOfShots                     &lt;dbl&gt; 0.13, 3.16, 1.…
$ I_F_reboundxGoals                                       &lt;dbl&gt; 0.07, 0.25, 0.…
$ I_F_xGoals_with_earned_rebounds                         &lt;dbl&gt; 2.27, 11.57, 2…
$ I_F_xGoals_with_earned_rebounds_scoreAdjusted           &lt;dbl&gt; 2.27, 11.55, 2…
$ I_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted     &lt;dbl&gt; 2.14, 10.97, 2…
$ I_F_shifts                                              &lt;dbl&gt; 105, 2026, 148…
$ I_F_oZoneShiftStarts                                    &lt;dbl&gt; 26, 284, 137, …
$ I_F_dZoneShiftStarts                                    &lt;dbl&gt; 25, 317, 171, …
$ I_F_neutralZoneShiftStarts                              &lt;dbl&gt; 25, 409, 330, …
$ I_F_flyShiftStarts                                      &lt;dbl&gt; 29, 1016, 842,…
$ I_F_oZoneShiftEnds                                      &lt;dbl&gt; 7, 250, 194, 1…
$ I_F_dZoneShiftEnds                                      &lt;dbl&gt; 10, 252, 195, …
$ I_F_neutralZoneShiftEnds                                &lt;dbl&gt; 20, 370, 252, …
$ I_F_flyShiftEnds                                        &lt;dbl&gt; 68, 1154, 839,…
$ faceoffsWon                                             &lt;dbl&gt; 0, 1, 1, 0, 0,…
$ faceoffsLost                                            &lt;dbl&gt; 0, 0, 0, 0, 0,…
$ timeOnBench                                             &lt;dbl&gt; 5938, 157427, …
$ penalityMinutes                                         &lt;dbl&gt; 6, 76, 60, 4, …
$ penalityMinutesDrawn                                    &lt;dbl&gt; 0, 26, 22, 0, …
$ penaltiesDrawn                                          &lt;dbl&gt; 0, 13, 11, 0, …
$ shotsBlockedByPlayer                                    &lt;dbl&gt; 3, 109, 85, 2,…
$ OnIce_F_xOnGoal                                         &lt;dbl&gt; 84.29, 906.45,…
$ OnIce_F_xGoals                                          &lt;dbl&gt; 13.21, 90.96, …
$ OnIce_F_flurryAdjustedxGoals                            &lt;dbl&gt; 12.22, 85.99, …
$ OnIce_F_scoreVenueAdjustedxGoals                        &lt;dbl&gt; 13.21, 91.04, …
$ OnIce_F_flurryScoreVenueAdjustedxGoals                  &lt;dbl&gt; 12.22, 86.01, …
$ OnIce_F_shotsOnGoal                                     &lt;dbl&gt; 92, 932, 586, …
$ OnIce_F_missedShots                                     &lt;dbl&gt; 38, 356, 218, …
$ OnIce_F_blockedShotAttempts                             &lt;dbl&gt; 38, 342, 210, …
$ OnIce_F_shotAttempts                                    &lt;dbl&gt; 168, 1630, 101…
$ OnIce_F_goals                                           &lt;dbl&gt; 11, 95, 59, 1,…
$ OnIce_F_rebounds                                        &lt;dbl&gt; 14, 77, 42, 2,…
$ OnIce_F_reboundGoals                                    &lt;dbl&gt; 3, 20, 13, 0, …
$ OnIce_F_lowDangerShots                                  &lt;dbl&gt; 82, 958, 619, …
$ OnIce_F_mediumDangerShots                               &lt;dbl&gt; 32, 243, 150, …
$ OnIce_F_highDangerShots                                 &lt;dbl&gt; 16, 87, 35, 1,…
$ OnIce_F_lowDangerxGoals                                 &lt;dbl&gt; 3.33, 28.82, 1…
$ OnIce_F_mediumDangerxGoals                              &lt;dbl&gt; 4.02, 29.82, 1…
$ OnIce_F_highDangerxGoals                                &lt;dbl&gt; 5.86, 32.32, 1…
$ OnIce_F_lowDangerGoals                                  &lt;dbl&gt; 4, 24, 19, 0, …
$ OnIce_F_mediumDangerGoals                               &lt;dbl&gt; 3, 35, 24, 1, …
$ OnIce_F_highDangerGoals                                 &lt;dbl&gt; 4, 36, 16, 0, …
$ OnIce_F_scoreAdjustedShotsAttempts                      &lt;dbl&gt; 168.00, 1623.4…
$ OnIce_F_unblockedShotAttempts                           &lt;dbl&gt; 130, 1288, 804…
$ OnIce_F_scoreAdjustedUnblockedShotAttempts              &lt;dbl&gt; 130.00, 1284.4…
$ OnIce_F_xGoalsFromxReboundsOfShots                      &lt;dbl&gt; 1.98, 15.11, 7…
$ OnIce_F_xGoalsFromActualReboundsOfShots                 &lt;dbl&gt; 3.60, 18.04, 9…
$ OnIce_F_reboundxGoals                                   &lt;dbl&gt; 3.26, 17.75, 9…
$ OnIce_F_xGoals_with_earned_rebounds                     &lt;dbl&gt; 11.22, 86.94, …
$ OnIce_F_xGoals_with_earned_rebounds_scoreAdjusted       &lt;dbl&gt; 11.22, 86.82, …
$ OnIce_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted &lt;dbl&gt; 10.55, 84.20, …
$ OnIce_A_xOnGoal                                         &lt;dbl&gt; 62.46, 790.57,…
$ OnIce_A_xGoals                                          &lt;dbl&gt; 12.64, 79.35, …
$ OnIce_A_flurryAdjustedxGoals                            &lt;dbl&gt; 12.11, 77.02, …
$ OnIce_A_scoreVenueAdjustedxGoals                        &lt;dbl&gt; 12.64, 79.92, …
$ OnIce_A_flurryScoreVenueAdjustedxGoals                  &lt;dbl&gt; 12.11, 77.57, …
$ OnIce_A_shotsOnGoal                                     &lt;dbl&gt; 65, 779, 546, …
$ OnIce_A_missedShots                                     &lt;dbl&gt; 30, 347, 234, …
$ OnIce_A_blockedShotAttempts                             &lt;dbl&gt; 23, 340, 247, …
$ OnIce_A_shotAttempts                                    &lt;dbl&gt; 118, 1466, 102…
$ OnIce_A_goals                                           &lt;dbl&gt; 11, 83, 44, 26…
$ OnIce_A_rebounds                                        &lt;dbl&gt; 10, 52, 33, 9,…
$ OnIce_A_reboundGoals                                    &lt;dbl&gt; 2, 14, 11, 1, …
$ OnIce_A_lowDangerShots                                  &lt;dbl&gt; 61, 841, 607, …
$ OnIce_A_mediumDangerShots                               &lt;dbl&gt; 16, 203, 133, …
$ OnIce_A_highDangerShots                                 &lt;dbl&gt; 18, 82, 40, 21…
$ OnIce_A_lowDangerxGoals                                 &lt;dbl&gt; 2.14, 25.35, 1…
$ OnIce_A_mediumDangerxGoals                              &lt;dbl&gt; 2.05, 24.13, 1…
$ OnIce_A_highDangerxGoals                                &lt;dbl&gt; 8.45, 29.87, 1…
$ OnIce_A_lowDangerGoals                                  &lt;dbl&gt; 3, 24, 14, 7, …
$ OnIce_A_mediumDangerGoals                               &lt;dbl&gt; 0, 24, 17, 6, …
$ OnIce_A_highDangerGoals                                 &lt;dbl&gt; 8, 35, 13, 13,…
$ OnIce_A_scoreAdjustedShotsAttempts                      &lt;dbl&gt; 118.00, 1474.1…
$ OnIce_A_unblockedShotAttempts                           &lt;dbl&gt; 95, 1126, 780,…
$ OnIce_A_scoreAdjustedUnblockedShotAttempts              &lt;dbl&gt; 95.00, 1130.82…
$ OnIce_A_xGoalsFromxReboundsOfShots                      &lt;dbl&gt; 1.24, 12.35, 7…
$ OnIce_A_xGoalsFromActualReboundsOfShots                 &lt;dbl&gt; 2.12, 11.59, 7…
$ OnIce_A_reboundxGoals                                   &lt;dbl&gt; 2.12, 11.93, 7…
$ OnIce_A_xGoals_with_earned_rebounds                     &lt;dbl&gt; 11.44, 78.40, …
$ OnIce_A_xGoals_with_earned_rebounds_scoreAdjusted       &lt;dbl&gt; 11.44, 78.89, …
$ OnIce_A_xGoals_with_earned_rebounds_scoreFlurryAdjusted &lt;dbl&gt; 11.10, 77.25, …
$ OffIce_F_xGoals                                         &lt;dbl&gt; 6.79, 95.61, 6…
$ OffIce_A_xGoals                                         &lt;dbl&gt; 12.11, 116.39,…
$ OffIce_F_shotAttempts                                   &lt;dbl&gt; 106, 2161, 167…
$ OffIce_A_shotAttempts                                   &lt;dbl&gt; 122, 2223, 164…
$ xGoalsForAfterShifts                                    &lt;dbl&gt; 0.14, 0.00, 3.…
$ xGoalsAgainstAfterShifts                                &lt;dbl&gt; 0.00, 0.00, 0.…
$ corsiForAfterShifts                                     &lt;dbl&gt; 4, 0, 91, 3, 6…
$ corsiAgainstAfterShifts                                 &lt;dbl&gt; 0, 0, 10, 0, 0…
$ fenwickForAfterShifts                                   &lt;dbl&gt; 3, 0, 74, 3, 6…
$ fenwickAgainstAfterShifts                               &lt;dbl&gt; 0, 0, 8, 0, 0,…</code></pre>
</div>
</div>
</section>
<section id="data-cleansing-and-breakout-idenitifcation" class="level3">
<h3 class="anchored" data-anchor-id="data-cleansing-and-breakout-idenitifcation">2.2 Data Cleansing and Breakout Idenitifcation</h3>
<p>The key variables used in our analysis from MoneyPuck are xgoals_per_game, games_played, and position. Based on MoneyPuck variables, we create goal_change, goals_per_game, xgoals_per_game, shots_per_game, and breakout. Below you will find an explanation of each of these variables.</p>
<p><strong>xgoals_per_game</strong> - Expected goals per game for each player. MoneyPuck’s Expected Goals Model determines this variable, and determines it to be “the chance of an unblocked shot attempt being a goal. For example, a rebound shot in the slot may have a 50% of going in and be worth 0.5 expected goals, while a shot from the blueline while short handed may be worth 0.01 expected goals.”</p>
<p><strong>games_played</strong> - Number of games played in a given season.</p>
<p><strong>position</strong> - Identification of a player’s position: center, right wing, left wing, defenseman.</p>
<p><strong>goal_change</strong> - A player’s next season goals minus current season goals.</p>
<p><strong>goals_per_game</strong> - Average goals scored per game by a player in a given season.</p>
<p><strong>xgoals_per_game</strong> - Average expected goals scored per game by a player in a given season.</p>
<p><strong>shots_per_game</strong> - Number of shots on goal per game by a player in a given season.</p>
<p><strong>breakout</strong> - binary variable, breakout players (1) are those players that rank in the top 10% of goal change and (0) if otherwise. In creating this variable, we decide to impose the 10 percent threshold as it is a reasonable requirement to identify those that are playing exceptionally well and have experienced high growth in performance since last season.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co">#clean the data</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>player_year <span class="ot">&lt;-</span> skaters_2008_to_2024 <span class="sc">%&gt;%</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(situation <span class="sc">==</span> <span class="st">"all"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(playerId, season) <span class="sc">%&gt;%</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(playerId) <span class="sc">%&gt;%</span> </span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">next_goals =</span> <span class="fu">lead</span>(I_F_goals),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">goal_change =</span> next_goals <span class="sc">-</span> I_F_goals) <span class="sc">%&gt;%</span> </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(goal_change), games_played<span class="sc">&gt;</span><span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">goals_per_game =</span> I_F_goals <span class="sc">/</span> games_played,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">shots_per_game =</span> I_F_shotsOnGoal <span class="sc">/</span> games_played,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">xgoals_per_game =</span> I_F_xGoals <span class="sc">/</span> games_played)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co">#define a breakout player</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>breakout_threshold <span class="ot">&lt;-</span> <span class="fu">quantile</span>(player_year<span class="sc">$</span>goal_change, <span class="fl">0.90</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>player_year <span class="ot">&lt;-</span> player_year <span class="sc">%&gt;%</span> </span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">breakout =</span> <span class="fu">ifelse</span>(goal_change <span class="sc">&gt;=</span> breakout_threshold, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co">#check</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(player_year<span class="sc">$</span>breakout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1173099</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>breakout_threshold</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>90% 
  7 </code></pre>
</div>
</div>
</section>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">2.3 Descriptive Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">#summary statistics table</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>player_year <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">N</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">n</span>(),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Breakout Rate (%)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(breakout) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Mean Goals</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(I_F_goals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Mean xGoals</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(I_F_xGoals, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Mean Shots on Goal</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(I_F_shotsOnGoal, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Mean Games Played</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(games_played, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">1</span>),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Share Defensemen (%)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(position <span class="sc">==</span> <span class="st">"D"</span>)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"Variable"</span>, <span class="at">values_to =</span> <span class="st">"Value"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Summary Statistics, MoneyPuck Dataset"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics, MoneyPuck Dataset</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: right;">12386.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Breakout Rate (%)</td>
<td style="text-align: right;">11.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean Goals</td>
<td style="text-align: right;">8.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean xGoals</td>
<td style="text-align: right;">8.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean Shots on Goal</td>
<td style="text-align: right;">89.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean Games Played</td>
<td style="text-align: right;">51.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Share Defensemen (%)</td>
<td style="text-align: right;">34.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Once cleansing the data, the dataset follows 12,386 player-seasons. For instance, one player does not equate to one variable, but rather has one variable for each of the seasons they competed in. Based on this data and the summary statistics table above, the mean breakout rate is 11.7% indicating that for every 10 player seasons, slightly more than one is classified as a breakout season. The average goals scored per season is 8.4, the average expected goals per season is slightly less at 8.3. Across each player-season, there was an average of 89.2 shots on goal and each of these players played an average of 51.3 games. The average share of defensemen across player-seasons is 34.5%.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Breakout Rate By Current Goal Total</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>player_year <span class="sc">|&gt;</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">goals_section =</span> <span class="fu">cut</span>(I_F_goals, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">30</span>, <span class="cn">Inf</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0-5"</span>, <span class="st">"6-15"</span>, <span class="st">"16-30"</span>, <span class="st">"30+"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(goals_section) <span class="sc">|&gt;</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">N</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">n</span>(),</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Breakout Rate (%)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(breakout) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))<span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Breakout Rate By Current Season Goal Total"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Breakout Rate By Current Season Goal Total</caption>
<thead>
<tr class="header">
<th style="text-align: left;">goals_section</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Breakout Rate (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0-5</td>
<td style="text-align: right;">6349</td>
<td style="text-align: right;">9.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">6-15</td>
<td style="text-align: right;">3643</td>
<td style="text-align: right;">15.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16-30</td>
<td style="text-align: right;">1997</td>
<td style="text-align: right;">13.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">30+</td>
<td style="text-align: right;">397</td>
<td style="text-align: right;">7.8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We then bucket goals into four groups: 0-5, 6-15, 16-30, and 30+. Organizing data in such a manner allows us to see the direct association between goals scored this season and breakout rate percentage. This is a really important finding that alters later interpretations of our results. As such, the “Breakout Rate by Current Season Goal Table” illuminates the fact that as goals scored increases beyond 6-15, predicted probability of a breakout season decreases. In this way, those that scored an average of 0 to 5 goals, had an average breakout rate percentage of 9.4, those that scored 6-15 had a 15.1 percentage, those that scored 16-30 had a 13.7 percentage rate, and those that scored 30+ goals had the lowest average breakout rate at 7.8 percent.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlations</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>cor_table <span class="ot">&lt;-</span> player_year <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(I_F_goals, next_goals, goal_change, I_F_xGoals, I_F_shotsOnGoal, games_played) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>cor_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 I_F_goals next_goals goal_change I_F_xGoals I_F_shotsOnGoal
I_F_goals        1.0000000  0.7512405  -0.3515417  0.9426499       0.8701021
next_goals       0.7512405  1.0000000   0.3538081  0.7517352       0.6740755
goal_change     -0.3515417  0.3538081   1.0000000 -0.2695698      -0.2769145
I_F_xGoals       0.9426499  0.7517352  -0.2695698  1.0000000       0.9014471
I_F_shotsOnGoal  0.8701021  0.6740755  -0.2769145  0.9014471       1.0000000
games_played     0.6090181  0.4066515  -0.2862448  0.6618317       0.7861908
                games_played
I_F_goals          0.6090181
next_goals         0.4066515
goal_change       -0.2862448
I_F_xGoals         0.6618317
I_F_shotsOnGoal    0.7861908
games_played       1.0000000</code></pre>
</div>
</div>
<p>This observed trend is further demonstrated in the above correlations table. As such, goals scored is negatively correlated with goal change, or the difference between a player’s next season goals and their current season goals. My personal hypothesis backing these findings is that I would suppose players that have reached an exceedingly high level of play, and have scored lots of goals, have a harder time substantially increasing their next season’s play. It might be easy to increase playing performance when one starts at a low point, but those players that are recognized as being strong, are marked more heavily, and have more of the other team’s attention on them, so this negative correlation does seem intuitive. On the other hand, next season goals correlates positively with the goal change variable. This makes sense given the consturuction of goal_change with next_goals being a component within it, so as next_goals increases so too should goal_change.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a figure</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_year, <span class="fu">aes</span>(<span class="at">x =</span> I_F_xGoals, <span class="at">y =</span> goal_change)) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Current Season xGoals vs Next Season Goal Increase"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Current Season Expected Goals"</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Next Season Goal Change"</span>)<span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_gov51_finalpaper_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#better figure</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(player_year, <span class="fu">aes</span>(<span class="at">x =</span> xgoals_per_game, <span class="at">y =</span> goal_change)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"xGoals per Game vs Next Season Goal Increase"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"xGoals per Game"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Next Season Goal Change"</span>)<span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_gov51_finalpaper_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In addition, these two graphs illustrate the extent to which high goal scoring and performance is associated with a smaller breakout rate. Given the line of best fit is negative for both current season expected goals and current season expected goals per game, we conclude that as these two measures increase in value, the goal change grows increasingly negative. With a smaller goal change, players will be less likely to be classified as a breakout player and achieve breakout status.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#For Positon Assumption</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>position_summary <span class="ot">&lt;-</span> player_year <span class="sc">%&gt;%</span> </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(position) <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Rate =</span> <span class="fu">mean</span>(breakout), <span class="at">N =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Rate))</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(position_summary, <span class="fu">aes</span>(<span class="at">x =</span> Rate, <span class="at">y =</span> <span class="fu">reorder</span>(position, Rate), <span class="at">fill =</span> position <span class="sc">==</span> <span class="st">"D"</span>)) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">percent</span>(Rate, <span class="at">accuracy =</span> <span class="fl">0.1</span>)), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"TRUE"</span> <span class="ot">=</span> <span class="st">"#2166AC"</span>, <span class="st">"FALSE"</span> <span class="ot">=</span> <span class="st">"#B2C8D9"</span>), <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">percent_format</span>(), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.65</span>)) <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="fu">labs</span>(</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="at">title =</span> <span class="st">"Breakout Rates Vary Substantially by Position"</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="at">subtitle =</span> <span class="st">"Share with top 10% goal increase next season, unadjusted"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a><span class="at">x =</span> <span class="st">"Breakout rate"</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a><span class="at">caption =</span> <span class="st">"Source: MoneyPuck"</span></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_gov51_finalpaper_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is also interesting to note how breakout rate differs by position. Intuitively, this adds up given defensemen are much farther away from the net at any given time than the offense with a 3.3% breakout rate. Intriguingly, left wings have the highest breakout rate at 17.6%, and right wings and centers follow closely behind at 15.9% and 15.4%. I suspect left wings have somewhat of an advantage in terms of shot quality or ability to release given that two thirds of NHL players are lefties and would have an advantage playing on the left side of the ice. Grondin et al.&nbsp;found that for left wings, those that were left handed players had a mean 0.184 goals per game and right handed players had a mean of 0.153 goals per game. This suggests that perhaps given the majority of NHLers are left handed, playing on the left side of the ice is more beneficial locational wise given their handedness. This is all just speculation on my part and something I found interesting outside of the data.</p>
<p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11339335/#:~:text=Results,Canada%2C%20Europe%2C%20or%20Russia." class="uri">https://pmc.ncbi.nlm.nih.gov/articles/PMC11339335/#:~:text=Results,Canada%2C%20Europe%2C%20or%20Russia.</a></p>
</section>
</section>
<section id="prediction-from-ols-to-logit-to-lasso" class="level2">
<h2 class="anchored" data-anchor-id="prediction-from-ols-to-logit-to-lasso">3 Prediction: From OLS to LOGIT to LASSO</h2>
<section id="traintest-split" class="level3">
<h3 class="anchored" data-anchor-id="traintest-split">3.1 Train/Test Split</h3>
<p>In an effort to mitigate the risk of overfitting, we create a training and test split of the data. As such, we group 70% of the data into a training set and the other 30% of the data into a test set. This allows us to train our model on known data and still be able to analyse its performance on new data. In this way, our training set consists of 8,670 observations and the test set has 3,716 observations. The training set is used for model fit, while the test set is used specifically to evaluate the model’s performance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#trail/test split</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>train_info <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(player_year), <span class="fl">0.7</span><span class="sc">*</span><span class="fu">nrow</span>(player_year))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> player_year[train_info, ]</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> player_year[<span class="sc">-</span>train_info, ]</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Training set:"</span>, <span class="fu">nrow</span>(train), <span class="st">"observations</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set: 8670 observations</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Test set:"</span>, <span class="fu">nrow</span>(test), <span class="st">"observations</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Test set: 3716 observations</code></pre>
</div>
</div>
</section>
<section id="baseline-ols-linear-probability-model" class="level3">
<h3 class="anchored" data-anchor-id="baseline-ols-linear-probability-model">3.2 Baseline: OLS (Linear Probability Model)</h3>
<p>After splitting the dataset into a train/test split, we perform a basic OLS regression. Given that our outcome variable, breakout, is a binary variable, this is identified as a Linear Probability Model. The according outputs reveal that shots on goal is positively associated with being a breakout player. On the other hand, games played and expected goals are negatively associated with being a breakout player. In terms of position, being a defenseman is associated with a 12.5 percentage points decrease in the probability of becoming breakout player.</p>
<p>It is also intriguing to note from our actual and predicted table that 1928 + 392 = 2,320 predicted breakout players out of a test set of 3,716. 2,320 / 3,716 = 0.6243, so our model predicts that about 62.43% of skaters will be breakout players. This is a very large percentage of players especially considering the actual breakout rate from our first summary statistics table was 11.7%. The major downside of this type of model, is that with a binary Y and continuous regressors, our regression can produce values that don’t lie between 0 and 1.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#basic ols</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(breakout <span class="sc">~</span> I_F_xGoals <span class="sc">+</span> I_F_shotsOnGoal <span class="sc">+</span> games_played <span class="sc">+</span> position, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> train)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = breakout ~ I_F_xGoals + I_F_shotsOnGoal + games_played + 
    position, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.3911 -0.1639 -0.1120 -0.0255  1.0236 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      0.2061048  0.0092613  22.254  &lt; 2e-16 ***
I_F_xGoals      -0.0032938  0.0012615  -2.611  0.00905 ** 
I_F_shotsOnGoal  0.0009740  0.0001535   6.346 2.32e-10 ***
games_played    -0.0020712  0.0002074  -9.988  &lt; 2e-16 ***
positionD       -0.1252290  0.0106286 -11.782  &lt; 2e-16 ***
positionL        0.0143479  0.0098531   1.456  0.14538    
positionR       -0.0097955  0.0104308  -0.939  0.34771    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3151 on 8663 degrees of freedom
Multiple R-squared:  0.04577,   Adjusted R-squared:  0.04511 
F-statistic: 69.26 on 6 and 8663 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict on test set</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>ols_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(mod1, <span class="at">newdata =</span> test)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>ols_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test<span class="sc">$</span>ols_pred <span class="sc">&gt;</span> <span class="fl">0.10</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Performance</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>ols_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test<span class="sc">$</span>breakout <span class="sc">-</span> test<span class="sc">$</span>ols_pred)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>ols_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>ols_class <span class="sc">==</span> test<span class="sc">$</span>breakout)</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"OLS — Test RMSE: %.4f | Accuracy: %.3f</span><span class="sc">\n</span><span class="st">"</span>, ols_rmse, ols_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS — Test RMSE: 0.3115 | Accuracy: 0.471</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">predicted =</span> test<span class="sc">$</span>ols_class, <span class="at">actual =</span> test<span class="sc">$</span>breakout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         actual
predicted    0    1
        0 1357   39
        1 1928  392</code></pre>
</div>
</div>
</section>
<section id="logit" class="level3">
<h3 class="anchored" data-anchor-id="logit">3.3 LOGIT</h3>
<p>We attempt to limit the above overprediction of breakout players and select a better fitting model by implementing a Logit model. This model mitigates the problem of extrapolation with continuous covariates and ensures that the the predicted probability will lie between 0 and 1. Once again, because our Y variable is binary, this is a more fitting result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#logit model because binary</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(breakout <span class="sc">~</span> xgoals_per_game <span class="sc">+</span> shots_per_game <span class="sc">+</span> games_played <span class="sc">+</span> position,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> train,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = breakout ~ xgoals_per_game + shots_per_game + games_played + 
    position, family = "binomial", data = train)

Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)     -1.97118    0.09407 -20.954  &lt; 2e-16 ***
xgoals_per_game  0.79741    0.67590   1.180    0.238    
shots_per_game   0.55788    0.08058   6.923 4.42e-12 ***
games_played    -0.01637    0.00142 -11.523  &lt; 2e-16 ***
positionD       -1.38603    0.13132 -10.555  &lt; 2e-16 ***
positionL        0.06540    0.08587   0.762    0.446    
positionR       -0.11376    0.09342  -1.218    0.223    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 6288.8  on 8669  degrees of freedom
Residual deviance: 5701.7  on 8663  degrees of freedom
AIC: 5715.7

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#OOS pred</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>pred_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test<span class="sc">$</span>pred_prob <span class="sc">&gt;</span> <span class="fl">0.10</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>logit_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test<span class="sc">$</span>breakout <span class="sc">-</span> test<span class="sc">$</span>pred_prob)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>logit_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>pred_class <span class="sc">==</span> test<span class="sc">$</span>breakout)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"LOGIT — Test RMSE: %.4f | Accuracy: %.3f</span><span class="sc">\n</span><span class="st">"</span>, logit_rmse, logit_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LOGIT — Test RMSE: 0.3091 | Accuracy: 0.548</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">predicted =</span> test<span class="sc">$</span>pred_class, <span class="at">actual =</span> test<span class="sc">$</span>breakout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         actual
predicted    0    1
        0 1674   70
        1 1611  361</code></pre>
</div>
</div>
<p>The Logit reveals that expected goals per game is not statistically significant and we fail to reject the null hypothesis that expected goals per game has no effect on breakout probability. On the other hand, shots per game is positively associated with a larger predicted probability of being a breakout player next season. 0.558 is the effect on the Logit function input of a unit change in shots per game holding expected goals per game, games played and position constant. As such, each additional shot per game is associated with the predicted probability of becoming a breakout player next season increasing by 74.4%, this is from using e^(0.558). On the other hand, each additional game played is associated with the predicted probability of becoming a breakout player next season decreasing by 1.6%, with 1 - e^(-0.016). Finally, being a defender is associated with the predicted probability of becoming a breakout player next season decreasing by 75.1%, with 1 - e^(-1.386), in relation to centers.</p>
<p>The resulting 1611 + 361 = 1972 predicted breakout players out of the 3,716 observation test set indicates that the model determines 53.07% of players to expect breakout seasons. This 53.07% value is substantially smaller than the OLS’s 62.43%, so the Logit model has fewer potential false positives in breakout than the baseline OLS Model. The accuracy of the Logit model also improves at 54.8% while the OLS’s accuracy was 47.1%.</p>
</section>
<section id="lasso" class="level3">
<h3 class="anchored" data-anchor-id="lasso">3.4 LASSO</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#LASSO</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>x_train <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(breakout <span class="sc">~</span> xgoals_per_game <span class="sc">+</span> shots_per_game <span class="sc">+</span> games_played <span class="sc">+</span> position, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> train)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> train<span class="sc">$</span>breakout</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>x_test <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(breakout <span class="sc">~</span> xgoals_per_game <span class="sc">+</span> shots_per_game <span class="sc">+</span> games_played <span class="sc">+</span> position, </span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> test)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co">#CV LASSO for lambda</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>lasso_cv <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(x_train, y_train, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">alpha =</span><span class="dv">1</span>)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso_cv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="piekarski_gov51_finalpaper_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>lambda1 <span class="ot">&lt;-</span> lasso_cv<span class="sc">$</span>lambda.min</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co">#ideal lambda incl</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>lasso1 <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(x_train, y_train, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">alpha =</span><span class="dv">1</span>, <span class="at">lambda =</span> lambda1)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>8 x 1 sparse Matrix of class "dgCMatrix"
                         s0
(Intercept)     -1.97846580
(Intercept)      .         
xgoals_per_game  0.83904630
shots_per_game   0.54040834
games_played    -0.01591686
positionD       -1.34717545
positionL        0.06506300
positionR       -0.09060354</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co">#predict with lambda min</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>lasso_prob <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(<span class="fu">predict</span>(lasso1, <span class="at">newx =</span> x_test, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>lasso_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(test<span class="sc">$</span>lasso_prob <span class="sc">&gt;</span> <span class="fl">0.10</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>lasso_rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test<span class="sc">$</span>breakout <span class="sc">-</span> test<span class="sc">$</span>lasso_prob)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>lasso_accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(test<span class="sc">$</span>lasso_class <span class="sc">==</span> test<span class="sc">$</span>breakout)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"LASSO — lambda.min: %.4f | Test RMSE: %.4f | Accuracy: %.3f</span><span class="sc">\n</span><span class="st">"</span>, </span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>            lambda1, lasso_rmse, lasso_accuracy))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>LASSO — lambda.min: 0.0007 | Test RMSE: 0.3090 | Accuracy: 0.544</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="at">predicted =</span> test<span class="sc">$</span>lasso_class, <span class="at">actual =</span> test<span class="sc">$</span>breakout)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         actual
predicted    0    1
        0 1661   69
        1 1624  362</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Which variables survive?</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>lasso_coef <span class="ot">&lt;-</span> <span class="fu">coef</span>(lasso_cv, <span class="at">s =</span> <span class="st">"lambda.min"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>nonzero <span class="ot">&lt;-</span> lasso_coef[lasso_coef[, <span class="dv">1</span>] <span class="sc">!=</span> <span class="dv">0</span>, , drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Nonzero coefficients: %d of %d</span><span class="sc">\n</span><span class="st">"</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>, <span class="fu">nrow</span>(nonzero) <span class="sc">-</span> <span class="dv">1</span>, <span class="fu">ncol</span>(x_train)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Nonzero coefficients: 6 of 7</code></pre>
</div>
</div>
<p>Finally, we come to our LASSO model, this least absolute shrinkage and selection operation, incorporates a penalty term, which shrinks some coefficients towards zero and sets others exactly to zero, highlighting selected variables to be used in the model. Our lambda or penalty error is selected by cross validation to find a lambda.min of 0.0007. This is a very small penalty error leading to 6 of 7 variables having nonzero coefficients. The resulting cross-validation curve, illustrates how a range of penalty errors impact model prediction error. Given the fact that the optimal lambda is so small, we can conclude that overfitting is not a problem in our model which should intuitively makes sense comparing 7 predictors to a training set of 8,670 observations. By performing the LASSO, our model accuracy increases from the baseline OLS which was 47.1% to 54.4% in the LASSO, yet it appears very similar to the Logit output with little to no changes.</p>
</section>
<section id="comparing-the-models" class="level3">
<h3 class="anchored" data-anchor-id="comparing-the-models">3.5 Comparing the Models</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">Model=</span> <span class="fu">c</span>(<span class="st">"OLS (no regularization)"</span>, <span class="st">"Logit"</span>, <span class="st">"LASSO (logit, lambda.min)"</span>),</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">`</span><span class="at">Test RMSE</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">c</span>(ols_rmse, logit_rmse, lasso_rmse), <span class="dv">4</span>),</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>       <span class="st">`</span><span class="at">Test Accuracy</span><span class="st">`</span><span class="ot">=</span> <span class="fu">percent</span>(<span class="fu">c</span>(ols_accuracy, logit_accuracy, lasso_accuracy), <span class="at">accuracy =</span> <span class="fl">0.1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Out-of-sample prediction performance: OLS vs. Logit vs. LASSO"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Out-of-sample prediction performance: OLS vs.&nbsp;Logit vs.&nbsp;LASSO</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Test RMSE</th>
<th style="text-align: left;">Test Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OLS (no regularization)</td>
<td style="text-align: right;">0.3115</td>
<td style="text-align: left;">47.1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Logit</td>
<td style="text-align: right;">0.3091</td>
<td style="text-align: left;">54.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LASSO (logit, lambda.min)</td>
<td style="text-align: right;">0.3090</td>
<td style="text-align: left;">54.4%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Ultimately, comparing the three models, we determine that the OLS, Logit, and LASSO provide telling insight but come with flaws. The OLS presents a test RMSE of 0.3115 and test accuracy of 47.1%, the Logit presents a test RMSE of 0.3091 and test accuracy of 54.8%, and the LASSO presents a test RMSE of 0.3090 and test accuracy of 54.4%. In comparing OLS and Logit, the Logit model is better as the RMSE decreases by 0.0024 and seems to intuitively make more sense based on our previous interpretations of the predicted and actual tables. However, when we compare Logit and LASSO, the results remain fairly consistent with the test RMSE decreasing by just 0.0001. This lack of substantial change suggests regularization does not do much, and our existing predictors are telling, but the breakout rate is just hard to predict with the largest test accuracy being from the Logit model at 54.8%</p>
</section>
</section>
<section id="fairness-does-the-model-predict-equally-across-positions" class="level2">
<h2 class="anchored" data-anchor-id="fairness-does-the-model-predict-equally-across-positions">4 Fairness: Does the Model Predict Equally Across Positions?</h2>
<p>Our models and earlier summary statistics indicated that there is tremendous variation in breakout rate by position. This table seeks to understand the difference between the mean actual breakout rate of players by position and the mean predicted probability of breakout players by position. From the outputs, we know the model slightly overpredicts breakout rate for centers and defenders while just underpredicting the breakout rate for left wings and right wings. Overall, these differences in actual versus mean predicted probability of breakout are quite small and the disparity between model prediction for differing positions is not substantially biased.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use Logit predictions </span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>test <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(position) <span class="sc">|&gt;</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">N =</span> <span class="fu">n</span>(),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">actual breakout rate (%)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(breakout<span class="sc">*</span><span class="dv">100</span>), <span class="dv">3</span>),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">mean predicted proabbility(%)</span><span class="st">`</span><span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(pred_prob<span class="sc">*</span><span class="dv">100</span>), <span class="dv">3</span>),</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">difference (pred - actual)</span><span class="st">`</span><span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(pred_prob<span class="sc">*</span><span class="dv">100</span>) <span class="sc">-</span> <span class="fu">mean</span>(breakout<span class="sc">*</span><span class="dv">100</span>), <span class="dv">3</span>),</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">.groups =</span> <span class="st">"drop"</span>)<span class="sc">|&gt;</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">"Mean Breakout Predicted probability Vs. Actual Breakout Rate by Position"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Mean Breakout Predicted probability Vs. Actual Breakout Rate by Position</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 5%">
<col style="width: 26%">
<col style="width: 31%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">position</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">actual breakout rate (%)</th>
<th style="text-align: right;">mean predicted proabbility(%)</th>
<th style="text-align: right;">difference (pred - actual)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">1092</td>
<td style="text-align: right;">15.110</td>
<td style="text-align: right;">15.595</td>
<td style="text-align: right;">0.486</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">1308</td>
<td style="text-align: right;">2.599</td>
<td style="text-align: right;">3.588</td>
<td style="text-align: right;">0.989</td>
</tr>
<tr class="odd">
<td style="text-align: left;">L</td>
<td style="text-align: right;">685</td>
<td style="text-align: right;">17.956</td>
<td style="text-align: right;">17.190</td>
<td style="text-align: right;">-0.766</td>
</tr>
<tr class="even">
<td style="text-align: left;">R</td>
<td style="text-align: right;">631</td>
<td style="text-align: right;">17.274</td>
<td style="text-align: right;">15.534</td>
<td style="text-align: right;">-1.740</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="top-predicted-breakouts" class="level2">
<h2 class="anchored" data-anchor-id="top-predicted-breakouts">5 Top Predicted Breakouts</h2>
<p>To place our model in the context of actual player information, we find that our model predicted the following 25 players to have the highest predicted probability of becoming breakout players in the following season. As indicated by the table, many of these players with the highest predicted probability of breakout did boast breakout seasons in the next season of play like Brandon Pirri, Brandeon Hagel, Zach Parise, Evgeni Malkin, and Sidney Crosby. However, many of these players with high predicted probability of breaking out do not end up having breakout seasons the following year like Marian Studenic, Miikka Salomaki, Nick Paul and Evan Rodrigues.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get players</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>predicted_breakouts <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pred_prob)) <span class="sc">%&gt;%</span> </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(name, season, position, pred_prob, breakout) <span class="sc">%&gt;%</span> </span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">25</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(predicted_breakouts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">season</th>
<th style="text-align: left;">position</th>
<th style="text-align: right;">pred_prob</th>
<th style="text-align: right;">breakout</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Brandon Pirri</td>
<td style="text-align: right;">2017</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.7796774</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marian Studenic</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.6682116</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Miikka Salomaki</td>
<td style="text-align: right;">2014</td>
<td style="text-align: left;">R</td>
<td style="text-align: right;">0.6620528</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nick Paul</td>
<td style="text-align: right;">2016</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.6557224</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Brandon Hagel</td>
<td style="text-align: right;">2019</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.6113313</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evan Rodrigues</td>
<td style="text-align: right;">2015</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.6074353</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matt Coronato</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">R</td>
<td style="text-align: right;">0.5797135</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zach Parise</td>
<td style="text-align: right;">2010</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.5553278</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Evgeni Malkin</td>
<td style="text-align: right;">2010</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.5231771</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sidney Crosby</td>
<td style="text-align: right;">2011</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4879795</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Auston Matthews</td>
<td style="text-align: right;">2021</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4876860</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nathan MacKinnon</td>
<td style="text-align: right;">2020</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4871883</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adam Henrique</td>
<td style="text-align: right;">2010</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4853210</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alex Ovechkin</td>
<td style="text-align: right;">2014</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.4846751</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Warren Foegele</td>
<td style="text-align: right;">2017</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.4806394</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jack Eichel</td>
<td style="text-align: right;">2021</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4793956</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eric Wellwood</td>
<td style="text-align: right;">2010</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.4762486</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ryan Poehling</td>
<td style="text-align: right;">2018</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4733809</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nathan MacKinnon</td>
<td style="text-align: right;">2021</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4698121</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tyler Angle</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4584333</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nathan MacKinnon</td>
<td style="text-align: right;">2023</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">0.4512573</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">David Pastrnak</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">R</td>
<td style="text-align: right;">0.4459676</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vladimir Sobotka</td>
<td style="text-align: right;">2016</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.4363039</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taylor Hall</td>
<td style="text-align: right;">2018</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.4324259</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Evander Kane</td>
<td style="text-align: right;">2022</td>
<td style="text-align: left;">L</td>
<td style="text-align: right;">0.4296821</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">6 Limitations</h2>
<p>One of the most obvious limitations of this paper is omitted variable bias. One such omitted variable could be player compatibility. Hockey players take extremely short shifts, and practice together for extended amounts of time, so their productivity may differ depending on who they are on a line with. This study fails to acknowledge the important aspect that some players simply work better together than others, and coaching decision and quality to execute good lines proves to be another omitted variable on top of that.</p>
<p>Applied to this study, player compatibility would impact the breakout dependent variable, as players will play better if they are working with those they have a connection with and this means they could have an increased goal_change difference. Considering the OVB formula α1 = β1 + β2γ1, the sign of β2 is likely positive. In addition, player compatibility is correlated with a regressor of interest, like shots per game, given that if you are playing with someone you gel well with, there can be an aspect of telephathy where one player knows where the other will be before they are even there. This relationship allows for heightened passing and shooting opportunites, and γ1 would thus have a positive sign. All of this considered, the net effect of β2γ1 is positive. We have overstated the true effect, estimating an effect (α1) larger in magnitude than that of the true effect (β1).</p>
<p>It is also important to note that we do not have a complete understanding of the model MoneyPuck uses to generate an expected goals value. Tanner specifices that the model determines this variable via computing the chance that an unblocked shot attempt becomes a goal. For instance, 0.5 expected goals could come from a rebound shot in the slot that has a 50% chance of becoming a goal, and 0.01 expected goals could result from a shot from the blueline while short handed. Ultimately, while compelling, the information stemming from this variable must be interpreted with a grain of salt given the lack of total understanding of its creation without the specific coding creation made public.</p>
<p>The results of this paper do not suggest causation. The purpose is to provide a predictive model of future breakout players. For future alterations of this project I would look to try to incorporate hard to quantiy variables by using fixed effects. Reflecting on the variables included, I do believe it would be beneficial to add in a variable for ice time given the fact that shifts in hockey are so short and inconsistent. It could also be interesting to explore what these outcomes may have looked like if the 10% threshold on breakout had been larger. I would assume under this scenario we may observe more accurate prediction on test sets.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">7 Conclusion</h2>
<p>In the end, this paper seeked to explore whether one could predict which players in the NHL will have a breakout season in the following year using statistical performance data from a given season. We conclude that this process is possible, although extremely challenging to do accurately. Given the substantial amount of variables difficult to quantify and potential confounding factors, its important to acknowledge the relevant limitations of the created models, when interpreting our findings.</p>
<p>On the larger scale, current NHL statistics provide many predictive models of who will win games and previous sports statistics on player performance. However, there is a lack of understanding of whether we can predict which players will excel in next season’s performance in relation to their performance this past season. Predictive player modelling, as is done in this paper, will provide extremely telling insight into which player’s are currently undervalued in the league. As the NHL continues to grow in popularity, revenue, and valuation, the stakes continue to rise, making the impact of predictive player statistics increasingly important.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>